version: '3'
services:
  directus:
    image: directus/directus:latest
    environment:
      DATABASE_HOST: ${DIRECTUS_DATABASE_HOST}
      DATABASE_PORT: ${DIRECTUS_DATABASE_PORT}
      DATABASE_NAME: ${DIRECTUS_DATABASE_NAME}
      DATABASE_USER: ${DIRECTUS_DATABASE_USER}
      DATABASE_PASSWORD: ${DIRECTUS_DATABASE_PASSWORD}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      ADMIN_FIRST_NAME: ${DIRECTUS_ADMIN_FIRST_NAME}
      ADMIN_LAST_NAME: ${DIRECTUS_ADMIN_LAST_NAME}
    ports:
      - '8055:8055'
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
